const {
  VITE_TOKEN_MOD_SPEC,
  VITE_OFFER_MOD_SPEC,
  VITE_BUY_MOD_SPEC,
  VITE_SALE_MOD_SPEC,
  VITE_SWAP_MOD_SPEC,
  VITE_PAYMENT_MOD_SPEC
} = import.meta.env
export {
  VITE_TOKEN_MOD_SPEC,
  VITE_OFFER_MOD_SPEC,
  VITE_BUY_MOD_SPEC,
  VITE_SALE_MOD_SPEC,
  VITE_SWAP_MOD_SPEC,
  VITE_PAYMENT_MOD_SPEC
}
