const { 
  REACT_APP_TOKEN_MOD_SPEC, 
  REACT_APP_OFFER_MOD_SPEC, 
  REACT_APP_BUY_MOD_SPEC,
  REACT_APP_SALE_MOD_SPEC,
  REACT_APP_SWAP_MOD_SPEC, 
  REACT_APP_PAYMENT_MOD_SPEC 
} = process.env
export { 
  REACT_APP_TOKEN_MOD_SPEC, 
  REACT_APP_OFFER_MOD_SPEC, 
  REACT_APP_BUY_MOD_SPEC,
  REACT_APP_SALE_MOD_SPEC,
  REACT_APP_SWAP_MOD_SPEC, 
  REACT_APP_PAYMENT_MOD_SPEC
}
