packages/BRC20
packages/BRC721
packages/chat
packages/create-react-app-template
packages/fungible-token
packages/node-js-boilerplate
packages/non-fungible-token
packages/react-app-ts-template
packages/wallet
packages/node

Dockerfile.explorer
Dockerfile.explorer.dockerignore

Dockerfile.node
Dockerfile.node.dockerignore