const { VITE_NFT_MOD_SPEC, VITE_OFFER_MOD_SPEC, VITE_SALE_MOD_SPEC, VITE_PAYMENT_MOD_SPEC } =
  import.meta.env
export { VITE_NFT_MOD_SPEC, VITE_OFFER_MOD_SPEC, VITE_SALE_MOD_SPEC, VITE_PAYMENT_MOD_SPEC }
