const { REACT_APP_NFT_MOD_SPEC, REACT_APP_OFFER_MOD_SPEC, REACT_APP_SALE_MOD_SPEC, REACT_APP_PAYMENT_MOD_SPEC } = process.env
export { REACT_APP_NFT_MOD_SPEC, REACT_APP_OFFER_MOD_SPEC, REACT_APP_SALE_MOD_SPEC, REACT_APP_PAYMENT_MOD_SPEC }
