services:
  db:
    image: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - bcn
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./chain-setup/${BCN_CHAIN}/${BCN_NETWORK}/db-data:/var/lib/postgresql/data
      - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
  node:
    image: ${BITCOIN_IMAGE}
    networks:
      - bitcoin
    restart: always
    ports:
      - ${BITCOIN_RPC_PORT}:${BITCOIN_RPC_PORT}
      - ${BCN_ZMQ_PORT}:${BCN_ZMQ_PORT}
    volumes:
      - ./chain-setup/${BCN_CHAIN}/${BCN_NETWORK}/blockchain-data:${BITCOIN_DATA_DIR}
      - ./${BITCOIN_CONF_FILE}:${BITCOIN_DATA_DIR}/${BITCOIN_CONF_FILE}
  bcn:
    image: bcdb/bcn
    env_file: .env
    restart: always
    build: ../../
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${BCN_PORT}/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: npm run start:bcn
    working_dir: /dist/packages/node
    ports:
      - ${BCN_PORT}:${BCN_PORT}
    environment:
      - BCN_CHAIN=${BCN_CHAIN}
      - BCN_NETWORK=${BCN_NETWORK}
      - BCN_ENV=${BCN_ENV}
      - BCN_URL=${BCN_URL}
      - BCN_ZMQ_URL=${BCN_ZMQ_URL}
      - BITCOIN_RPC_HOST=${BITCOIN_RPC_HOST}
      - BITCOIN_RPC_PORT=${BITCOIN_RPC_PORT}
      - BITCOIN_RPC_PROTOCOL=${BITCOIN_RPC_PROTOCOL}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - db
      - node
    networks:
      - bitcoin
      - bcn
    volumes:
      - ./logs:/dist/packages/node/logs
  sync:
    command: npm run start:sync
    image: bcdb/bcn
    env_file: .env
    restart: always
    environment:
      - BCN_CHAIN=${BCN_CHAIN}
      - BCN_NETWORK=${BCN_NETWORK}
      - BCN_ENV=${BCN_ENV}
      - BCN_URL=${BCN_URL}
      - BCN_ZMQ_URL=${BCN_ZMQ_URL}
      - BCN_WORKER_ID=${BCN_WORKER_ID}
      - BCN_NUM_WORKERS=${BCN_NUM_WORKERS}
      - BITCOIN_RPC_HOST=${BITCOIN_RPC_HOST}
      - BITCOIN_RPC_PORT=${BITCOIN_RPC_PORT}
      - BITCOIN_RPC_PROTOCOL=${BITCOIN_RPC_PROTOCOL}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./logs:/dist/packages/node/logs
    depends_on:
      - db
      - node
    networks:
      - bitcoin
      - bcn
networks:
  bitcoin: null
  bcn: null
