// flow-typed signature: a65d6a0579c444e8be0d3e825479e89f
// flow-typed version: <<STUB>>/babel-preset-minify_v^0.5.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-minify' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-minify/lib/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'babel-preset-minify/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-minify/lib/index'>
}
