// flow-typed signature: f2753131b38f7d6a5a17961815d35c8c
// flow-typed version: <<STUB>>/bs58_v=2.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs58'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs58' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs58/lib/bs58' {
  declare module.exports: any
}

// Filename aliases
declare module 'bs58/lib/bs58.js' {
  declare module.exports: $Exports<'bs58/lib/bs58'>
}
