// flow-typed signature: 06eda215386866ca8b979c457f5bd37b
// flow-typed version: <<STUB>>/buffer-compare_v=1.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-compare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-compare' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buffer-compare/test/test' {
  declare module.exports: any
}

// Filename aliases
declare module 'buffer-compare/index' {
  declare module.exports: $Exports<'buffer-compare'>
}
declare module 'buffer-compare/index.js' {
  declare module.exports: $Exports<'buffer-compare'>
}
declare module 'buffer-compare/test/test.js' {
  declare module.exports: $Exports<'buffer-compare/test/test'>
}
