// flow-typed signature: d9ff90f1f21716b4eb6c97c71a7bf10d
// flow-typed version: <<STUB>>/cashaddrjs_v^0.2.9/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cashaddrjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cashaddrjs' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cashaddrjs/dist/cashaddrjs-0.2.9' {
  declare module.exports: any
}

declare module 'cashaddrjs/dist/cashaddrjs-0.2.9.min' {
  declare module.exports: any
}

declare module 'cashaddrjs/LICENSE' {
  declare module.exports: any
}

declare module 'cashaddrjs/src/base32' {
  declare module.exports: any
}

declare module 'cashaddrjs/src/cashaddr' {
  declare module.exports: any
}

declare module 'cashaddrjs/src/convertBits' {
  declare module.exports: any
}

declare module 'cashaddrjs/src/validation' {
  declare module.exports: any
}

// Filename aliases
declare module 'cashaddrjs/dist/cashaddrjs-0.2.9.js' {
  declare module.exports: $Exports<'cashaddrjs/dist/cashaddrjs-0.2.9'>
}
declare module 'cashaddrjs/dist/cashaddrjs-0.2.9.min.js' {
  declare module.exports: $Exports<'cashaddrjs/dist/cashaddrjs-0.2.9.min'>
}
declare module 'cashaddrjs/LICENSE.js' {
  declare module.exports: $Exports<'cashaddrjs/LICENSE'>
}
declare module 'cashaddrjs/src/base32.js' {
  declare module.exports: $Exports<'cashaddrjs/src/base32'>
}
declare module 'cashaddrjs/src/cashaddr.js' {
  declare module.exports: $Exports<'cashaddrjs/src/cashaddr'>
}
declare module 'cashaddrjs/src/convertBits.js' {
  declare module.exports: $Exports<'cashaddrjs/src/convertBits'>
}
declare module 'cashaddrjs/src/validation.js' {
  declare module.exports: $Exports<'cashaddrjs/src/validation'>
}
