// flow-typed signature: 291b360960eed6ed876faffbb26b31c8
// flow-typed version: <<STUB>>/hash.js_v^1.1.7/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hash.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hash.js' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hash.js/lib/hash' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/common' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/hmac' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/ripemd' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/sha' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/sha/1' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/sha/224' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/sha/256' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/sha/384' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/sha/512' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/sha/common' {
  declare module.exports: any
}

declare module 'hash.js/lib/hash/utils' {
  declare module.exports: any
}

declare module 'hash.js/test/hash-test' {
  declare module.exports: any
}

declare module 'hash.js/test/hmac-test' {
  declare module.exports: any
}

// Filename aliases
declare module 'hash.js/lib/hash.js' {
  declare module.exports: $Exports<'hash.js/lib/hash'>
}
declare module 'hash.js/lib/hash/common.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/common'>
}
declare module 'hash.js/lib/hash/hmac.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/hmac'>
}
declare module 'hash.js/lib/hash/ripemd.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/ripemd'>
}
declare module 'hash.js/lib/hash/sha.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/sha'>
}
declare module 'hash.js/lib/hash/sha/1.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/sha/1'>
}
declare module 'hash.js/lib/hash/sha/224.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/sha/224'>
}
declare module 'hash.js/lib/hash/sha/256.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/sha/256'>
}
declare module 'hash.js/lib/hash/sha/384.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/sha/384'>
}
declare module 'hash.js/lib/hash/sha/512.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/sha/512'>
}
declare module 'hash.js/lib/hash/sha/common.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/sha/common'>
}
declare module 'hash.js/lib/hash/utils.js' {
  declare module.exports: $Exports<'hash.js/lib/hash/utils'>
}
declare module 'hash.js/test/hash-test.js' {
  declare module.exports: $Exports<'hash.js/test/hash-test'>
}
declare module 'hash.js/test/hmac-test.js' {
  declare module.exports: $Exports<'hash.js/test/hmac-test'>
}
