// flow-typed signature: 5d946ffea5a5d233a1bc63d4c207dfb3
// flow-typed version: <<STUB>>/randombytes_v^2.1.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randombytes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'randombytes' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'randombytes/browser' {
  declare module.exports: any
}

declare module 'randombytes/test' {
  declare module.exports: any
}

// Filename aliases
declare module 'randombytes/browser.js' {
  declare module.exports: $Exports<'randombytes/browser'>
}
declare module 'randombytes/index' {
  declare module.exports: $Exports<'randombytes'>
}
declare module 'randombytes/index.js' {
  declare module.exports: $Exports<'randombytes'>
}
declare module 'randombytes/test.js' {
  declare module.exports: $Exports<'randombytes/test'>
}
