// flow-typed signature: af1fe62b326e71027bd6cd438e36eddd
// flow-typed version: <<STUB>>/unorm_v^1.4.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unorm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unorm' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unorm/lib/unorm' {
  declare module.exports: any
}

// Filename aliases
declare module 'unorm/lib/unorm.js' {
  declare module.exports: $Exports<'unorm/lib/unorm'>
}
