import * as address from './address.js';
import * as crypto from './crypto.js';
import * as networks from './networks.js';
import { p2ms, p2pk, p2pkh, p2sh, p2wpkh, p2wsh, p2tr } from './payments/index.js';
import * as script from './script.js';
import * as bip371 from './psbt/bip371.js';
import * as bufferUtils from './bufferutils.js';
declare const payments: {
    p2ms: typeof p2ms;
    p2pk: typeof p2pk;
    p2pkh: typeof p2pkh;
    p2sh: typeof p2sh;
    p2wpkh: typeof p2wpkh;
    p2wsh: typeof p2wsh;
    p2tr: typeof p2tr;
};
export { address, crypto, networks, payments, script, bufferUtils };
export { Block } from './block.js';
export { TaggedHashPrefix } from './crypto.js';
export { Psbt, PsbtTxInput, PsbtTxOutput, Signer, SignerAsync, HDSigner, HDSignerAsync, } from './psbt.js';
export { OPS as opcodes } from './ops.js';
export { Transaction } from './transaction.js';
export { Network } from './networks.js';
export { Payment, PaymentCreator, PaymentOpts, Stack, StackElement, } from './payments/index.js';
export { Input as TxInput, Output as TxOutput } from './transaction.js';
export { initEccLib } from './ecc_lib.js';
export { bip371 };
