services:
  db:
    env_file: .env
    volumes:
      - ./chain-setup/pepe-testnet/db-data:/var/lib/postgresql/data
      - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    restart: always
  node:
    image: pepeenthusiast/pepecoin-core:1.0.1
    networks:
      - bitcoin
    restart: always
    command:
      [
        "pepecoind",
        "-testnet=1",
        "-dbcache=4000",
        "-txindex=1",
        "-printtoconsole=1",
        "-server=1",
        "-rpcbind=0.0.0.0",
        "-rpcworkqueue=512",
        "-rpcport=44873",
        "-port=44874",
        "-zmqpubhashtx=tcp://0.0.0.0:28332",
        "-zmqpubrawtx=tcp://0.0.0.0:28332",
        "-rpcallowip=0.0.0.0/0",
        "-rpcauth=${RPC_AUTH}",
        "-wallet=${DEFAULT_WALLET}"
      ]
    ports:
      - 44874:44874
      - 44873:44873
      - 28332:28332
    volumes:
      - ./chain-setup/pepe-testnet/blockchain-data:/home/pepecoin/.pepecoin
  bcn:
    image: bitcoin-computer-node
    env_file: .env
    restart: always
    environment:
      - BCN_ENV=dev
      - RPC_HOST=node
      - RPC_PORT=44873
      - ZMQ_URL=tcp://node:28332
      - NETWORK=testnet
      - CHAIN=PEPE
      - BCN_URL=https://tpepe.node.bitcoincomputer.io
    depends_on:
      - db
      - node
  sync:
    command: npm run sync
    image: bitcoin-computer-node
    env_file: .env
    restart: always
    environment:
      - BCN_ENV=dev
      - RPC_HOST=node
      - RPC_PORT=44873
      - NETWORK=testnet
      - CHAIN=PEPE
      - ZMQ_URL=tcp://node:28332
      - BCN_URL=https://tpepe.node.bitcoincomputer.io
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - RPC_PROTOCOL=http
      - RPC_USER=${RPC_USER}
      - RPC_PASSWORD=${RPC_PASSWORD}
      - THREADS=${THREADS}
    volumes:
      - ./logs:/dist/packages/node/logs
    depends_on:
      - db
      - node
    networks:
      - bitcoin
      - bcn
  