version: '3'
services:
  express-app:
    env_file: .env
    build: .
    image: chess-server
    volumes:
      - ./src:/app/src
    ports:
      - '4000:4000'
    networks:
      - express-app
    depends_on:
      - postgres
networks:
  express-app: null
