version: '3'
services:
  express-app:
    env_file: .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    build: .
    image: chess-server
    volumes:
      - ./src:/app/src
    ports:
      - '4000:4000'
    networks:
      - express-app
    depends_on:
      - postgres
  postgres:
    image: postgres
    env_file: .env
    ports:
      - '5434:5432'
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
      - ./db/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    networks:
      - express-app
networks:
  express-app: null
